name: Build and Deploy Journal
on:
 push:
   branches: [ main ]
   paths: [ 'journal.txt' ]
jobs:
 build-and-deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v3
   - name: Setup Node.js
     uses: actions/setup-node@v3
     with:
       node-version: '18'
   - name: Generate HTML
     run: node build.js
   - name: Commit generated files
     run: |
       git config --local user.email "action@github.com"
       git config --local user.name "GitHub Action"
       git add index.html
       git commit -m "Update journal" || exit 0
       git push
